# Generated by Django 4.1.6 on 2023-02-02 08:27

from django.db import migrations, models
import django.db.models.deletion
import genie_backend.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenieUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(help_text='Discord에 기록되는 고유한 유저의 hash된 id 값', max_length=100, unique=True, verbose_name='Discord id')),
                ('name', models.CharField(help_text='Discord nickname', max_length=50, verbose_name='이름')),
                ('discriminator', models.IntegerField(help_text='Discord discriminator', verbose_name='Discriminator')),
                ('avatar', models.URLField(blank=True, default='', help_text='Discord Profile URL', null=True, verbose_name='Discord Profile')),
            ],
            options={
                'verbose_name': '디스코드 유저 정보',
                'verbose_name_plural': '디스코드 유저 정보',
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='블록체인 네트워크 이름', max_length=30, unique=True, verbose_name='이름')),
            ],
            options={
                'verbose_name': '블록체인 네트워크',
                'verbose_name_plural': '블록체인 네트워크',
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='지갑주소', max_length=100, unique=True, verbose_name='지갑주소')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns_wallet', to='accounts.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='accounts.genieuser')),
            ],
            options={
                'verbose_name': '유저 지갑 정보',
                'verbose_name_plural': '유저 지갑 정보',
            },
            bases=(models.Model, genie_backend.utils.models.PrintableMixin),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('network', 'address'), name='unique wallet address'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'network', 'address'), name='Wallet can be owned by only one user'),
        ),
    ]
